language: java
jdk:
- oraclejdk8
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_dc2bc48c1933_key -iv $encrypted_dc2bc48c1933_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- mysql -e 'CREATE DATABASE IF NOT EXISTS dareondb;'

addons:
  ssh_known_hosts: 130.56.249.92

script:
- ls target
